options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Build logs will be sent only to Cloud Logging.

steps:
  # Step 1: Build the Docker image for the Python Flask app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA', '.']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  # Step 3: Deploy the green version of the service (with environment variable API_KEY)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'production-green',
      '--image', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'COLOR=green,API_KEY=${_API_KEY}'  # Set the color and API_KEY environment variables
    ]

  # Step 4: Deploy the blue version of the service (with environment variable API_KEY)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'production-blue',
      '--image', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'COLOR=blue,API_KEY=${_API_KEY}'  # Set the color and API_KEY environment variables
    ]

  # Step 5: Split traffic between blue and green revisions
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'services', 'update-traffic', 'production',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--to-revisions', 'production-blue-00001-9hp=50,production-green-00001-abc=50'
    ]