options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Build logs will be sent only to Cloud Logging.

steps:
  # Step 1: Build Docker image and push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-docker.pkg.dev/cot4930-001/your-repo-name/your-image-name:${SHORT_SHA}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-docker.pkg.dev/cot4930-001/your-repo-name/your-image-name:${SHORT_SHA}'

# Define the image URI
images:
  - 'asia-docker.pkg.dev/cot4930-001/your-repo-name/your-image-name:${SHORT_SHA}'

# Step 2: Deploy to Cloud Run with Traffic Splitting
substitutions:
  _NEW_VERSION_TAG: 'your-image-name:${SHORT_SHA}'
  _CLOUD_RUN_SERVICE: 'production'  # Existing service name (can be 'blue' if already deployed)

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - 'green'  # The new version that will handle 50% of the traffic
    - '--image'
    - 'asia-docker.pkg.dev/cot4930-001/your-repo-name/${_NEW_VERSION_TAG}'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--project'
    - 'cot4930-001'
    - '--traffic'
    - '50=green'   # 50% of the traffic goes to the new version (green)
    - '50=blue'    # 50% of the traffic goes to the old version (blue)