options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Build logs will be sent only to Cloud Logging.

steps:
  # Step 1: Build the Docker image for the Python Flask app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA', '.']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  # Step 3: Deploy the Docker image to Cloud Run (Green Version)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'production-green',  # Cloud Run service name for green version
      '--image', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'COLOR=green'  # Set the color to green for this revision
    ]

  # Step 4: Deploy the Docker image to Cloud Run (Blue Version)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'production-blue',  # Cloud Run service name for blue version
      '--image', 'us-docker.pkg.dev/cot4930-001/automationcd/colored-page:$COMMIT_SHA',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'COLOR=blue'  # Set the color to blue for this revision
    ]

  # Step 5: Split traffic 50/50 between revisions (Green and Blue)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'services', 'update-traffic', 'production',  # Cloud Run service name (use 'production')
      '--region', 'us-east1',
      '--platform', 'managed',
      '--to-revisions', 'production-green=50,production-blue=50'  # Split traffic 50/50
    ]