options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Build logs will be sent only to Cloud Logging.

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA', '.']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  # Step 3: Deploy the new image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'production',  # Cloud Run service name is 'production'
      '--image', 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA',  # Corrected image name
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Step 4: Split traffic 50/50 between the new and the previous revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'services', 'update-traffic', 'production',  # Cloud Run service name
      '--region', 'us-east1',
      '--platform', 'managed',
      '--to-revision', 'production',  # Traffic to the new revision
      '--split', '50=production,50=previous-revision'  # Adjust according to your revision names
    ]
