options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Build logs will be sent only to Cloud Logging.

steps:
  # Step 1: Build Docker image for the Blue Version (using the same Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cot4930-001/automationcd/production-blue:$COMMIT_SHA', '.']

  # Step 2: Build Docker image for the Green Version (using the same Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cot4930-001/automationcd/production-green:$COMMIT_SHA', '.']

  # Step 3: Run tests (optional, modify based on your testing framework)
  - name: 'gcr.io/cloud-builders/python'
    args: ['-m', 'unittest', 'discover']

  # Step 4: Push Blue Version Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cot4930-001/automationcd/production-blue:$COMMIT_SHA']

  # Step 5: Push Green Version Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cot4930-001/automationcd/production-green:$COMMIT_SHA']

  # Step 6: Deploy Blue Version to Cloud Run with Background Color Set to Blue
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'production-blue'
      - '--image'
      - 'us-docker.pkg.dev/cot4930-001/automationcd/production-blue:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'BACKGROUND_COLOR=blue'

  # Step 7: Deploy Green Version to Cloud Run with Background Color Set to Green
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'production-green'
      - '--image'
      - 'us-docker.pkg.dev/cot4930-001/automationcd/production-green:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'BACKGROUND_COLOR=green'

  # Step 8: Split Traffic Between Blue and Green Versions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'production'
      - '--to-latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--traffic'
      - 'production-blue=50,production-green=50'

timeout: 1200s  # Set timeout as needed