options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Build logs will be sent only to Cloud Logging.

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA', '.']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA']
    env:
      - 'API_KEY=${_API_KEY}'  # Reference the environment variable directly

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'production',
         '--image', 'gcr.io/cot4930-001/automationcd:$SHORT_SHA',
         '--region', 'us-east1',
         '--platform', 'managed',
         '--allow-unauthenticated' # or other ingress settings
         # Add any other necessary Cloud Run flags
        ]


images:
  - 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA'

# You can omit substitutions if using an environment variable from the build environment directly
