options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Build logs will be sent only to Cloud Logging.

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA', '.']
    env:
      - 'API_KEY=${_API_KEY}'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA']
    env:
      - 'API_KEY=${_API_KEY}'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'production'  # Cloud Run service name is 'production'
      - '--image'
      - 'us-docker.pkg.dev/cot4930-001/automationcd/production:$COMMIT_SHA'  # Make sure $COMMIT_SHA is unique
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

        # Step 4: Update Traffic to the New Revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'services', 'update-traffic', 'production',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--to-revisions', '$(gcloud run revisions list --service=production --region=us-east1 --platform=managed --filter="status.state=READY" --format="value(METADATA.NAME)" | head -n 1)=100'
    ]